

url=https://test.intercellworld.com/
login_dashboard_url=https://test.intercellworld.com/account/dashboard
user=iamsachingaba@gmail.com
pass=intercell@123

invalid_pass=inter@123

login_error_msg=Sorry! Username and Password not matching

//profile Updation

firstname=Sachin
lastname=TestSelenium
Gender=Male
Country=India
State=Haryana
City=Sirsa
year=1995
Experience=12


//browser

browser=chrome


//booking
randomText1=Enter some test here1
randomText2=Enter some test here2
randomText3=Enter some test here3
randomText4=Enter some test here4
randomText5=Enter some test here5


Mentor=Sachinj00i Gaba

