

url=https://test.intercellworld.com/
login_dashboard_url=https://test.intercellworld.com/account/dashboard
user=iamsachingaba@gmail.com
pass=intercell@123

invalid_pass=inter@123

login_error_msg=Sorry! Username and Password not matching

//profile Updation

firstname=Sachin
lastname=TestSelenium
Gender=Male
Country=India
State=Haryana
City=Sirsa
year=1995