

url=https://test.intercellworld.com/
login_dashboard_url=https://test.intercellworld.com/account/dashboard
user=iamsachingaba@gmail.com
pass=intercell@123

invalid_pass=inter@123

login_error_msg=Sorry! Username and Password not matching

